defaults:
  - _self_
  - override model: hedger
  - override data: regimes
  - override algorithm: irm
  - override training: default
  - override evaluation: default
  - override logging: wandb

project:
  name: hirm_experiment
  seed: 0
  output_dir: outputs/reproduce

hydra:
  run:
    dir: ${project.output_dir}
  output_subdir: null

wandb:
  mode: disabled
